#!/bin/bash
REPO_PATH="$HOME/dotfiles"

check_directory_and_create_link() {
    if [ ! -d "$HOME/.$1" ]; then
        ln -s "$REPO_PATH/$1" "$HOME/.$1" &&
            echo "Link to '$HOME/.$1' created"
    else
        echo "The directory $HOME/.$1 already exists, link not created"
    fi
}

check_file_and_create_link() {
    if [ ! -f "$HOME/.$1" ]; then
        ln -s "$REPO_PATH/$1" "$HOME/.$1" &&
            echo "Link to '$HOME/.$1' created"
    else
        echo "The file $HOME/.$1 already exists, link not created"
    fi
}


# Shell configuration
check_file_and_create_link "profile"

# Bash configuration
check_file_and_create_link "bash_logout"
check_file_and_create_link "bashrc"
check_directory_and_create_link "bash-mod"

# Vim stuff
check_file_and_create_link "viminfo"
check_file_and_create_link "vimrc"
check_directory_and_create_link "vim"

# Emacs stuff
check_directory_and_create_link "emacs.d"

# i3 stuff
# i3 config
[ ! -f "$HOME/.config/i3/" ] && mkdir -p "$HOME/.config/i3/"
if [ ! -f "$HOME/.config/i3/config" ]; then
    ln -s "$REPO_PATH/i3_config" "$HOME/.config/i3/config" &&
        echo "Link to '$HOME/.config/i3/config' created"
else
    echo "The file $HOME/.config/i3/config already exists, link not created"
fi

# i3bar config
[ ! -f "$HOME/.config/i3status/" ] && mkdir -p "$HOME/.config/i3status/"
if [ ! -f "$HOME/.config/i3status/config" ]; then
    ln -s "$REPO_PATH/i3status_config" "$HOME/.config/i3status/config" &&
        echo "Link to '$HOME/.config/i3status/config' created"
else
    echo "The file $HOME/.config/i3status/config already exists, link not created"
fi
# dm config file
check_file_and_create_link "dmrc"

# Git config file
check_file_and_create_link "gitconfig"

# Feh background config file
check_file_and_create_link "fehbg"
