#!/bin/bash
# Conjunto de chorradicas y experimentos para hacerme esto mas comodo
#
# Autor: Guillermo Robles

if uname -a | grep SunOS > /dev/null
then
	alias ls="\ls"
fi
export MOD=1
if [ -n "$MOD" ]; then

    # Carga de colecciones de comandos en otros archivos
    # shellcheck source=/home/guillermo/.bash-mod/alias
    . "$HOME/.bash-mod/alias"  # Alias
    # shellcheck source=/home/guillermo/.bash-mod/colors
    . "$HOME/.bash-mod/colors" # Colores
    # shellcheck source=/home/guillermo/.bash-mod/emacs
    . "$HOME/.bash-mod/emacs"  # Emacs
    # shellcheck source=/home/guillermo/.bash-mod/prompt
    . "$HOME/.bash-mod/prompt" # Prompt
    # shellcheck source=/home/guillermo/.bash-mod/youtube-dl
    . "$HOME/.bash-mod/youtube-dl" # Youtube-dl
    # shellcheck source=/home/guillermo/.bash-mod/vagrant
    . "$HOME/.bash-mod/vagrant" # Vagrant
    # shellcheck source=opt-programs
    . "$HOME/.bash-mod/opt-programs"
    # shellcheck source=go-stuff
    . "$HOME/.bash-mod/go-stuff"
    # shellcheck source=juju
    . "$HOME/.bash-mod/juju"
    # shellcheck source=latex
    . "$HOME/.bash-mod/latex"
    # shellcheck source=packaging
    . "$HOME/.bash-mod/packaging"

    alias sudo='sudo '

    # Adiciones al PATH y a otras variables
    # Directorio actual
    export PATH="$HOME/bin:$PATH"
    export PATH="$HOME/.cabal/bin:$PATH"

    # Otras variables interesantes
    export HISTCONTROL=ignoreboth # Evitar duplicados en la historia de BASH
    PROMPT_COMMAND='history -a' # Guardar el historial en cada ejecucion de comando

    echo "You should try to read the manpage of one of these: $(random-man -s -n 3)"
fi
