#!/bin/bash
alias idea=~/opt/idea/bin/idea.sh
alias nuclear='~/opt/nuclear-throne/nuclear-throne'
alias eclipse-rcp='~/opt/eclipse-rcp/eclipse'
# Strike the earth!
alias dw='$HOME/opt/df/df'
alias android-studio='$HOME/opt/android-studio/bin/studio.sh'
alias sonar-scanner='$HOME/opt/sonar-scanner/bin/sonar-scanner'
alias weka='$HOME/opt/weka-3-8-1/weka'
