#!/bin/bash
alias skype=~/opt/skype/skype
alias idea=~/opt/idea/bin/idea.sh
alias nuclear='~/opt/nuclear-throne/nuclear-throne'
alias eclipse-rcp='~/opt/eclipse-rcp/eclipse'
# Strike the earth!
alias dw='$HOME/opt/df/df'
