#!/bin/bash
# Author: Guillermo Robles
#
# Prompt modifications


git_prompt_zero_changes () {
    [ "$(git status -s 2>/dev/null | wc -l)" = "0" ]
}


git_prompt () {
    if git_prompt_zero_changes; then
        __git_ps1 ' (%s)'
    else
        __git_ps1 ' {%s}'
    fi
}

git_prompt_color () {
    if git_prompt_zero_changes; then
        echo -e "\033[1;32m"
    else
        echo -e "\033[1;31m"
    fi
}

# Show state of last command only if it was different from 0
SELECT="OUT=\$?;if [ \${OUT} != 0 ]; then echo \":(\[\033[1;31m\]\${OUT}\[\033[1;33m\])\"; fi"
# Save old PS1
export OLD_PS1=$PS1
export PS1="\[\033[1;33m\]\u\$(${SELECT}):\w\[\$(git_prompt_color)\]\$(git_prompt)\[\033[1;33m\]\$\[\033[0m\] "

print_pre_prompt () {
    TIME=$(date +%H:%M)
    printf "\e[1;37m%${COLUMNS}s" "${TIME}"
}

# PROMPT_COMMAND=print_pre_prompt
