#!/bin/bash
#
# Comandos relacionados con sql y cuentas

export VICIOUS_HOST="${CUENTA_UNI}@vicious.hendrix-oracle.cps.unizar.es"
alias sql-vicious="sqlplus \${VICIOUS_HOST}"

alias mysql-miniFlights="mysql -u a604409 -h hendrix-mysql.cps.unizar.es -p miniFlights"
alias mysql-miniIMDB="mysql -u a604409 -h hendrix-mysql.cps.unizar.es -p miniIMDB"

